[global]
developmentMode = false
showWarningOnDirectExecution = false

[server]
runOnSave = true
port = 8501
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 10
maxMessageSize = 10

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#FF9A8B"
backgroundColor = "#FDFEFE"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#2C3E50"
font = "sans serif"

[client]
caching = true
displayEnabled = true
